pipeline {
    agent any

    environment {
        IMAGE_NAME = "gabriellova/auth-service"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install') {
            steps { sh 'npm install' }
        }

        stage('Build Docker') {
            steps { sh 'docker build -t $IMAGE_NAME:latest .' }
        }

        stage('Push Docker') {
            steps { sh 'docker push $IMAGE_NAME:latest' }
        }

        stage('Deploy') {
            steps { sh 'kubectl apply -f ../../k8s/auth/' }
        }
    }
}
